#!/bin/bash
set -e

create_link()
{
    if ! test -e $HOME/$2; then
        echo "Creating sym link $2 to $1"
        ln -s $PWD/$1 $HOME/$2
    else
        echo "$2 already exists, skip"
    fi
}


install_package()
{
    case $(uname) in
        Darwin)
            cmd="brew install"
            ;;
        Linux)
            cmd="sudo apt-get install -y"
            ;;
    esac
    $cmd $@
}

fix_user_dirs()
{
    (cd $HOME; mkdir -p down doc music pic video)
    create_link user-dirs.dirs .config/user-dirs.dirs
    xdg-user-dirs-update || true
}

install_rust()
{
    if test -d $HOME/.cargo; then echo rust already installed, skip.; return 0; fi
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
}

create_link vimrc .vim
create_link bin bin
create_link gitconfig .gitconfig
create_link gitignore .gitignore_global
create_link bashrc .bashrc
create_link i3 .config/i3

for x in $(ls bin); do
    create_link bin/$x bin/$x
done
install_package curl wget sysstat git vim-gtk3 cscope make gcc silversearcher-ag python3-pip ccache bison flex
pip3 install powerline-status
fix_user_dirs
install_rust
