syntax on

" Always show status
set autoindent
set smartindent
set autowriteall
set background=dark
set backspace=indent,eol,start
set laststatus=2
set number
set smartcase
set ignorecase
set incsearch
set hlsearch
set hidden
set undodir=~/.cache/vimundo
set undofile
set list
set listchars=tab:>-
silent !mkdir -p ~/.cache/vimundo

" Cursor shape
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

let mapleader = ","

if has("gui_running")
  " GUI is running or is about to start.
  " Maximize gvim window (for an alternative on Windows, see simalt below).
  set lines=999 columns=999
  "set guifont=Terminus\ 12
  set guioptions-=m  "remove menu bar
  set guioptions-=T  "remove toolbar
  set guioptions-=r  "remove right-hand scroll bar
  set guioptions-=L  "remove left-hand scroll bar
  set mouse=v
  set clipboard=autoselectplus
endif

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.cache/vimplug')

" Make sure you use single quotes

Plug 'farmergreg/vim-lastplace'
" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

Plug 'mattn/emmet-vim'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
" Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
" Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
" Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'do': './install --all' }
Plug 'junegunn/fzf.vim'
nnoremap <C-p> :Files<CR>
nnoremap <leader>m :History<CR>
nnoremap <leader>b :Buffer<CR>
nnoremap Y y$
nnoremap <F7> :make<CR>
nnoremap <C-]> :tjump <C-R><C-W><CR>
vnoremap <C-c> "+y

Plug 'majutsushi/tagbar'

Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

Plug 'morhetz/gruvbox'

Plug 'rust-lang/rust.vim'

nnoremap <silent> <leader>g :vimgrep "\C\<<C-R><C-W>\>"/\C %<CR>:call Highlighting()<CR>:cw<CR>:silent set hlsearch<CR>

" Plug 'dkprice/vim-easygrep'
" let g:EasyGrepJumpToMatch=0
" function! Highlighting()
"   let @/ = '\<'.expand('<cword>').'\>'
" endfunction
" " Map global search to EasyGrep command
" nnoremap <silent> <leader>G :Ggrep "\<<C-R><C-W>\>"<CR>:cw<CR>
" nnoremap <leader>? :Ggrep 

Plug 'gabesoft/vim-ags'
let g:ags_agcontext = 0
nnoremap <Leader>G :Ags<Space><C-R>=expand('<cword>')<CR><CR>

nnoremap <f5> :make run<CR>
inoremap <f5> <ESC>:make run<CR>

Plug 'posva/vim-vue'

" Plug 'dylanaraps/root.vim'
" let g:root#auto = 1
" let g:root#echo = 0

" Initialize plugin system
call plug#end()

nnoremap <leader>T :TagbarToggle<CR>

nnoremap QQ :qall<CR>
inoremap <C-v> <Esc>"+gpa

command W w !sudo tee "%" > /dev/null

au BufEnter * call MyLastWindow()
function! MyLastWindow()
  " if the window is quickfix go on
  if &buftype=="quickfix"
    " if this window is last on screen quit without warning
    if winbufnr(2) == -1
      quit!
    endif
  endif
endfunction

autocmd FileType yaml set shiftwidth=2 | set tabstop=4
autocmd FileType markdown set shiftwidth=4 | set tabstop=4
autocmd FileType make set shiftwidth=8 | set tabstop=8
autocmd Filetype c,cpp,rust set cino+=(0
autocmd Filetype rust nmap <F8> :make test<CR>

function SensibleIndent()
    if getcwd() =~ "/linux"
        set noet
        set ts=8
        set sw=8
    endif
endfunction
autocmd BufEnter *.[ch] call SensibleIndent()
autocmd BufEnter *.[ch]pp call SensibleIndent()

colorscheme gruvbox

set tabstop=4 shiftwidth=4 expandtab
autocmd filetype html,css,javascript,javascriptreact,typescript,yaml,vue,typescriptreact setlocal tabstop=2 shiftwidth=2 expandtab
